# -*- coding: utf-8 -*-
"""pydf_tts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPVx9wSF3IkWOXgzhIb-DfbTOZBF14_6
"""

!pip install streamlit

!pip install pymupdf

!pip install pyttsx3

import streamlit as st
import fitz
import pyttsx3
import os

def extract_text_from_pdf(pdf_file):
    doc = fitz.open(streamlit_uploaded_file=pdf_file)
    text = ""
    for page in doc:
        text += page.get_text("text") + "\n"
    return text

def text_to_speech(text):
    engine = pyttsx3.init()
    engine.save_to_file(text, "output_audio.mp3")  # Save as audio file
    engine.runAndWait()

st.title("PDF to Speech Converter")

uploaded_file = st.file_uploader("Upload a PDF file", type="pdf")

if uploaded_file is not None:
    text = extract_text_from_pdf(uploaded_file)
    st.text_area("Extracted Text", text, height=300)

    if st.button("Convert to Speech"):
        text_to_speech(text)
        st.audio("output_audio.mp3", format="audio/mp3", start_time=0)